CREATE DATABASE IF NOT EXISTS smartfarming;
USE smartfarming;

CREATE TABLE IF NOT EXISTS sensor_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    moisture INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pump_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    status VARCHAR(10) NOT NULL,
    source VARCHAR(20) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
